import type { Metadata } from "next";
import { Luckiest_Guy, } from "next/font/google";
import "./globals.css";


const luckiestGuy = Luckiest_Guy({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${luckiestGuy.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
